name: Create Feature Request
description: 新機能の提案や機能改善の要望
title: "[Feature]: "
labels: ["enhancement", "wontfix", "feature"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        新機能の提案や機能改善の要望を提出していただき、ありがとうございます。以下のフォームにご記入ください。

  - type: textarea
    id: motivation
    attributes:
      label: 背景・動機
      description: この機能が必要な理由や、解決したい問題について教えてください
      placeholder: 現状の課題や、なぜこの機能が必要なのかを具体的に記述してください
    validations:
      required: false

  - type: textarea
    id: proposed-solution
    attributes:
      label: 提案内容
      description: どのような機能を追加・改善したいのかを具体的に教えてください
      placeholder: 機能の詳細や、期待する動作について記述してください
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 検討した他の解決方法があれば教えてください
      placeholder: 他に考えられる実装方法や解決策があれば記述してください
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この機能の優先度をお選びください
      options:
        - 高（すぐに必要）
        - 中（あれば便利）
        - 低（いつかあれば）
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 補足情報
      description: スクリーンショットや参考資料などの追加情報があれば添付してください
      placeholder: 関連する情報や注意点があれば記述してください

  - type: checkboxes
    id: terms
    attributes:
      label: 確認事項
      description: 以下の項目を確認の上、チェックしてください
      options:
        - label: 同様の機能要望が既に存在しないことを確認しました
          required: true
        - label: この機能が本プロジェクトの目的に沿っていることを確認しました
          required: true
